add_executable(m711-gui main.c)
target_include_directories(m711-gui PRIVATE ${GTK4_INCLUDE_DIRS})
target_link_directories(m711-gui PRIVATE ${GTK4_LIBRARY_DIRS})
target_compile_options(m711-gui PRIVATE ${GTK4_CFLAGS_OTHER})
target_link_libraries(m711-gui PRIVATE m711::m711 ${GTK4_LIBRARIES} m)
install(TARGETS m711-gui RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
