add_executable(bluedragon-gui main.c)
target_include_directories(bluedragon-gui PRIVATE ${GTK4_INCLUDE_DIRS})
target_link_directories(bluedragon-gui PRIVATE ${GTK4_LIBRARY_DIRS})
target_compile_options(bluedragon-gui PRIVATE ${GTK4_CFLAGS_OTHER})
target_link_libraries(bluedragon-gui PRIVATE bluedragon::bluedragon ${GTK4_LIBRARIES} m)
install(TARGETS bluedragon-gui RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
